// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: commitments.sql

package store

import (
	"context"
	"database/sql"
)

const countCommitments = `-- name: CountCommitments :one
SELECT COUNT(*) FROM commitments WHERE provider = ?
`

func (q *Queries) CountCommitments(ctx context.Context, provider string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCommitments, provider)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCommitmentsOlderThan = `-- name: DeleteCommitmentsOlderThan :exec
DELETE FROM commitments WHERE period_start < ?
`

func (q *Queries) DeleteCommitmentsOlderThan(ctx context.Context, periodStart string) error {
	_, err := q.db.ExecContext(ctx, deleteCommitmentsOlderThan, periodStart)
	return err
}

const getAggregatedCommitmentMetrics = `-- name: GetAggregatedCommitmentMetrics :one
SELECT
    COALESCE(SUM(total_commitment), 0) AS total_commitment,
    COALESCE(SUM(used_commitment), 0) AS used_commitment,
    COALESCE(SUM(net_savings), 0) AS net_savings,
    CASE WHEN SUM(total_commitment) > 0
        THEN SUM(used_commitment) * 100.0 / SUM(total_commitment)
        ELSE 0
    END AS avg_utilization,
    currency
FROM commitments
WHERE provider = ? AND period_start >= ? AND period_end <= ?
GROUP BY currency
`

type GetAggregatedCommitmentMetricsParams struct {
	Provider    string `json:"provider"`
	PeriodStart string `json:"period_start"`
	PeriodEnd   string `json:"period_end"`
}

type GetAggregatedCommitmentMetricsRow struct {
	TotalCommitment interface{} `json:"total_commitment"`
	UsedCommitment  interface{} `json:"used_commitment"`
	NetSavings      interface{} `json:"net_savings"`
	AvgUtilization  int64       `json:"avg_utilization"`
	Currency        string      `json:"currency"`
}

func (q *Queries) GetAggregatedCommitmentMetrics(ctx context.Context, arg GetAggregatedCommitmentMetricsParams) (GetAggregatedCommitmentMetricsRow, error) {
	row := q.db.QueryRowContext(ctx, getAggregatedCommitmentMetrics, arg.Provider, arg.PeriodStart, arg.PeriodEnd)
	var i GetAggregatedCommitmentMetricsRow
	err := row.Scan(
		&i.TotalCommitment,
		&i.UsedCommitment,
		&i.NetSavings,
		&i.AvgUtilization,
		&i.Currency,
	)
	return i, err
}

const getCommitmentSummary = `-- name: GetCommitmentSummary :many
SELECT commitment_type,
    SUM(total_commitment) AS total_commitment,
    SUM(used_commitment) AS used_commitment,
    SUM(on_demand_equivalent) AS on_demand_equivalent,
    SUM(net_savings) AS net_savings,
    currency
FROM commitments
WHERE provider = ? AND period_start >= ? AND period_end <= ?
GROUP BY commitment_type, currency
ORDER BY commitment_type
`

type GetCommitmentSummaryParams struct {
	Provider    string `json:"provider"`
	PeriodStart string `json:"period_start"`
	PeriodEnd   string `json:"period_end"`
}

type GetCommitmentSummaryRow struct {
	CommitmentType     string          `json:"commitment_type"`
	TotalCommitment    sql.NullFloat64 `json:"total_commitment"`
	UsedCommitment     sql.NullFloat64 `json:"used_commitment"`
	OnDemandEquivalent sql.NullFloat64 `json:"on_demand_equivalent"`
	NetSavings         sql.NullFloat64 `json:"net_savings"`
	Currency           string          `json:"currency"`
}

func (q *Queries) GetCommitmentSummary(ctx context.Context, arg GetCommitmentSummaryParams) ([]GetCommitmentSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommitmentSummary, arg.Provider, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCommitmentSummaryRow{}
	for rows.Next() {
		var i GetCommitmentSummaryRow
		if err := rows.Scan(
			&i.CommitmentType,
			&i.TotalCommitment,
			&i.UsedCommitment,
			&i.OnDemandEquivalent,
			&i.NetSavings,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommitmentSummaryByAccount = `-- name: GetCommitmentSummaryByAccount :many
SELECT account_id, commitment_type,
    SUM(total_commitment) AS total_commitment,
    SUM(used_commitment) AS used_commitment,
    SUM(on_demand_equivalent) AS on_demand_equivalent,
    SUM(net_savings) AS net_savings,
    currency
FROM commitments
WHERE provider = ? AND period_start >= ? AND period_end <= ?
GROUP BY account_id, commitment_type, currency
ORDER BY account_id, commitment_type
`

type GetCommitmentSummaryByAccountParams struct {
	Provider    string `json:"provider"`
	PeriodStart string `json:"period_start"`
	PeriodEnd   string `json:"period_end"`
}

type GetCommitmentSummaryByAccountRow struct {
	AccountID          string          `json:"account_id"`
	CommitmentType     string          `json:"commitment_type"`
	TotalCommitment    sql.NullFloat64 `json:"total_commitment"`
	UsedCommitment     sql.NullFloat64 `json:"used_commitment"`
	OnDemandEquivalent sql.NullFloat64 `json:"on_demand_equivalent"`
	NetSavings         sql.NullFloat64 `json:"net_savings"`
	Currency           string          `json:"currency"`
}

func (q *Queries) GetCommitmentSummaryByAccount(ctx context.Context, arg GetCommitmentSummaryByAccountParams) ([]GetCommitmentSummaryByAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommitmentSummaryByAccount, arg.Provider, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCommitmentSummaryByAccountRow{}
	for rows.Next() {
		var i GetCommitmentSummaryByAccountRow
		if err := rows.Scan(
			&i.AccountID,
			&i.CommitmentType,
			&i.TotalCommitment,
			&i.UsedCommitment,
			&i.OnDemandEquivalent,
			&i.NetSavings,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommitmentTrend = `-- name: GetCommitmentTrend :many
SELECT period_start, commitment_type,
    total_commitment,
    used_commitment,
    utilization_pct,
    coverage_pct,
    net_savings,
    currency
FROM commitments
WHERE provider = ? AND period_start >= ? AND period_end <= ?
ORDER BY period_start ASC, commitment_type
`

type GetCommitmentTrendParams struct {
	Provider    string `json:"provider"`
	PeriodStart string `json:"period_start"`
	PeriodEnd   string `json:"period_end"`
}

type GetCommitmentTrendRow struct {
	PeriodStart     string  `json:"period_start"`
	CommitmentType  string  `json:"commitment_type"`
	TotalCommitment float64 `json:"total_commitment"`
	UsedCommitment  float64 `json:"used_commitment"`
	UtilizationPct  float64 `json:"utilization_pct"`
	CoveragePct     float64 `json:"coverage_pct"`
	NetSavings      float64 `json:"net_savings"`
	Currency        string  `json:"currency"`
}

func (q *Queries) GetCommitmentTrend(ctx context.Context, arg GetCommitmentTrendParams) ([]GetCommitmentTrendRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommitmentTrend, arg.Provider, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCommitmentTrendRow{}
	for rows.Next() {
		var i GetCommitmentTrendRow
		if err := rows.Scan(
			&i.PeriodStart,
			&i.CommitmentType,
			&i.TotalCommitment,
			&i.UsedCommitment,
			&i.UtilizationPct,
			&i.CoveragePct,
			&i.NetSavings,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCommitment = `-- name: UpsertCommitment :exec
INSERT INTO commitments (provider, account_id, commitment_type, period_start, period_end, total_commitment, used_commitment, on_demand_equivalent, net_savings, utilization_pct, coverage_pct, currency, synced_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(provider, account_id, commitment_type, period_start)
DO UPDATE SET
    period_end = excluded.period_end,
    total_commitment = excluded.total_commitment,
    used_commitment = excluded.used_commitment,
    on_demand_equivalent = excluded.on_demand_equivalent,
    net_savings = excluded.net_savings,
    utilization_pct = excluded.utilization_pct,
    coverage_pct = excluded.coverage_pct,
    currency = excluded.currency,
    synced_at = excluded.synced_at
`

type UpsertCommitmentParams struct {
	Provider           string  `json:"provider"`
	AccountID          string  `json:"account_id"`
	CommitmentType     string  `json:"commitment_type"`
	PeriodStart        string  `json:"period_start"`
	PeriodEnd          string  `json:"period_end"`
	TotalCommitment    float64 `json:"total_commitment"`
	UsedCommitment     float64 `json:"used_commitment"`
	OnDemandEquivalent float64 `json:"on_demand_equivalent"`
	NetSavings         float64 `json:"net_savings"`
	UtilizationPct     float64 `json:"utilization_pct"`
	CoveragePct        float64 `json:"coverage_pct"`
	Currency           string  `json:"currency"`
	SyncedAt           string  `json:"synced_at"`
}

func (q *Queries) UpsertCommitment(ctx context.Context, arg UpsertCommitmentParams) error {
	_, err := q.db.ExecContext(ctx, upsertCommitment,
		arg.Provider,
		arg.AccountID,
		arg.CommitmentType,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.TotalCommitment,
		arg.UsedCommitment,
		arg.OnDemandEquivalent,
		arg.NetSavings,
		arg.UtilizationPct,
		arg.CoveragePct,
		arg.Currency,
		arg.SyncedAt,
	)
	return err
}
