// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cost_records.sql

package store

import (
	"context"
	"database/sql"
)

const countCostRecords = `-- name: CountCostRecords :one
SELECT COUNT(*) FROM cost_records
`

func (q *Queries) CountCostRecords(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCostRecords)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCostRecordsByProvider = `-- name: CountCostRecordsByProvider :one
SELECT COUNT(*) FROM cost_records WHERE provider = ?
`

func (q *Queries) CountCostRecordsByProvider(ctx context.Context, provider string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCostRecordsByProvider, provider)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCostRecordsOlderThan = `-- name: DeleteCostRecordsOlderThan :exec
DELETE FROM cost_records WHERE period_start < ?
`

func (q *Queries) DeleteCostRecordsOlderThan(ctx context.Context, periodStart string) error {
	_, err := q.db.ExecContext(ctx, deleteCostRecordsOlderThan, periodStart)
	return err
}

const getCostByServiceForRegion = `-- name: GetCostByServiceForRegion :many
SELECT service, SUM(amount) AS total_amount, currency
FROM cost_records
WHERE provider = ? AND region = ? AND period_start >= ? AND period_end <= ?
GROUP BY service, currency
ORDER BY total_amount DESC
`

type GetCostByServiceForRegionParams struct {
	Provider    string         `json:"provider"`
	Region      sql.NullString `json:"region"`
	PeriodStart string         `json:"period_start"`
	PeriodEnd   string         `json:"period_end"`
}

type GetCostByServiceForRegionRow struct {
	Service     string          `json:"service"`
	TotalAmount sql.NullFloat64 `json:"total_amount"`
	Currency    string          `json:"currency"`
}

func (q *Queries) GetCostByServiceForRegion(ctx context.Context, arg GetCostByServiceForRegionParams) ([]GetCostByServiceForRegionRow, error) {
	rows, err := q.db.QueryContext(ctx, getCostByServiceForRegion,
		arg.Provider,
		arg.Region,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCostByServiceForRegionRow{}
	for rows.Next() {
		var i GetCostByServiceForRegionRow
		if err := rows.Scan(&i.Service, &i.TotalAmount, &i.Currency); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCostRecordsByAccount = `-- name: GetCostRecordsByAccount :many
SELECT id, provider, account_id, service, region, period_start, period_end, granularity, amount, currency, synced_at FROM cost_records
WHERE provider = ? AND account_id = ?
ORDER BY period_start DESC
`

type GetCostRecordsByAccountParams struct {
	Provider  string `json:"provider"`
	AccountID string `json:"account_id"`
}

func (q *Queries) GetCostRecordsByAccount(ctx context.Context, arg GetCostRecordsByAccountParams) ([]CostRecord, error) {
	rows, err := q.db.QueryContext(ctx, getCostRecordsByAccount, arg.Provider, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CostRecord{}
	for rows.Next() {
		var i CostRecord
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.AccountID,
			&i.Service,
			&i.Region,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Granularity,
			&i.Amount,
			&i.Currency,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCostRecordsByAccountAndDateRange = `-- name: GetCostRecordsByAccountAndDateRange :many
SELECT id, provider, account_id, service, region, period_start, period_end, granularity, amount, currency, synced_at FROM cost_records
WHERE provider = ? AND account_id = ? AND period_start >= ? AND period_end <= ?
ORDER BY period_start DESC
`

type GetCostRecordsByAccountAndDateRangeParams struct {
	Provider    string `json:"provider"`
	AccountID   string `json:"account_id"`
	PeriodStart string `json:"period_start"`
	PeriodEnd   string `json:"period_end"`
}

func (q *Queries) GetCostRecordsByAccountAndDateRange(ctx context.Context, arg GetCostRecordsByAccountAndDateRangeParams) ([]CostRecord, error) {
	rows, err := q.db.QueryContext(ctx, getCostRecordsByAccountAndDateRange,
		arg.Provider,
		arg.AccountID,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CostRecord{}
	for rows.Next() {
		var i CostRecord
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.AccountID,
			&i.Service,
			&i.Region,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Granularity,
			&i.Amount,
			&i.Currency,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCostRecordsByDateRange = `-- name: GetCostRecordsByDateRange :many
SELECT id, provider, account_id, service, region, period_start, period_end, granularity, amount, currency, synced_at FROM cost_records
WHERE provider = ? AND period_start >= ? AND period_end <= ?
ORDER BY period_start DESC
`

type GetCostRecordsByDateRangeParams struct {
	Provider    string `json:"provider"`
	PeriodStart string `json:"period_start"`
	PeriodEnd   string `json:"period_end"`
}

func (q *Queries) GetCostRecordsByDateRange(ctx context.Context, arg GetCostRecordsByDateRangeParams) ([]CostRecord, error) {
	rows, err := q.db.QueryContext(ctx, getCostRecordsByDateRange, arg.Provider, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CostRecord{}
	for rows.Next() {
		var i CostRecord
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.AccountID,
			&i.Service,
			&i.Region,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Granularity,
			&i.Amount,
			&i.Currency,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCostRecordsByProvider = `-- name: GetCostRecordsByProvider :many
SELECT id, provider, account_id, service, region, period_start, period_end, granularity, amount, currency, synced_at FROM cost_records
WHERE provider = ?
ORDER BY period_start DESC
`

func (q *Queries) GetCostRecordsByProvider(ctx context.Context, provider string) ([]CostRecord, error) {
	rows, err := q.db.QueryContext(ctx, getCostRecordsByProvider, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CostRecord{}
	for rows.Next() {
		var i CostRecord
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.AccountID,
			&i.Service,
			&i.Region,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Granularity,
			&i.Amount,
			&i.Currency,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCostRecordsByService = `-- name: GetCostRecordsByService :many
SELECT id, provider, account_id, service, region, period_start, period_end, granularity, amount, currency, synced_at FROM cost_records
WHERE provider = ? AND service = ?
ORDER BY period_start DESC
`

type GetCostRecordsByServiceParams struct {
	Provider string `json:"provider"`
	Service  string `json:"service"`
}

func (q *Queries) GetCostRecordsByService(ctx context.Context, arg GetCostRecordsByServiceParams) ([]CostRecord, error) {
	rows, err := q.db.QueryContext(ctx, getCostRecordsByService, arg.Provider, arg.Service)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CostRecord{}
	for rows.Next() {
		var i CostRecord
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.AccountID,
			&i.Service,
			&i.Region,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Granularity,
			&i.Amount,
			&i.Currency,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctAccounts = `-- name: GetDistinctAccounts :many
SELECT DISTINCT account_id FROM cost_records
WHERE provider = ?
ORDER BY account_id
`

func (q *Queries) GetDistinctAccounts(ctx context.Context, provider string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctAccounts, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var account_id string
		if err := rows.Scan(&account_id); err != nil {
			return nil, err
		}
		items = append(items, account_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctRegions = `-- name: GetDistinctRegions :many
SELECT DISTINCT region FROM cost_records
WHERE provider = ? AND region IS NOT NULL
ORDER BY region
`

func (q *Queries) GetDistinctRegions(ctx context.Context, provider string) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctRegions, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var region sql.NullString
		if err := rows.Scan(&region); err != nil {
			return nil, err
		}
		items = append(items, region)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctServices = `-- name: GetDistinctServices :many
SELECT DISTINCT service FROM cost_records
WHERE provider = ?
ORDER BY service
`

func (q *Queries) GetDistinctServices(ctx context.Context, provider string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctServices, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var service string
		if err := rows.Scan(&service); err != nil {
			return nil, err
		}
		items = append(items, service)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestSyncedPeriod = `-- name: GetLatestSyncedPeriod :one
SELECT MAX(period_end) AS latest_period_end
FROM cost_records
WHERE provider = ? AND account_id = ?
`

type GetLatestSyncedPeriodParams struct {
	Provider  string `json:"provider"`
	AccountID string `json:"account_id"`
}

func (q *Queries) GetLatestSyncedPeriod(ctx context.Context, arg GetLatestSyncedPeriodParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLatestSyncedPeriod, arg.Provider, arg.AccountID)
	var latest_period_end interface{}
	err := row.Scan(&latest_period_end)
	return latest_period_end, err
}

const getMonthlyCostByAccount = `-- name: GetMonthlyCostByAccount :many
SELECT account_id, period_start, SUM(amount) AS total_amount, currency
FROM cost_records
WHERE provider = ? AND period_start >= ? AND period_end <= ?
GROUP BY account_id, period_start, currency
ORDER BY account_id, period_start ASC
`

type GetMonthlyCostByAccountParams struct {
	Provider    string `json:"provider"`
	PeriodStart string `json:"period_start"`
	PeriodEnd   string `json:"period_end"`
}

type GetMonthlyCostByAccountRow struct {
	AccountID   string          `json:"account_id"`
	PeriodStart string          `json:"period_start"`
	TotalAmount sql.NullFloat64 `json:"total_amount"`
	Currency    string          `json:"currency"`
}

func (q *Queries) GetMonthlyCostByAccount(ctx context.Context, arg GetMonthlyCostByAccountParams) ([]GetMonthlyCostByAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, getMonthlyCostByAccount, arg.Provider, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyCostByAccountRow{}
	for rows.Next() {
		var i GetMonthlyCostByAccountRow
		if err := rows.Scan(
			&i.AccountID,
			&i.PeriodStart,
			&i.TotalAmount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyCostTrend = `-- name: GetMonthlyCostTrend :many
SELECT period_start, SUM(amount) AS total_amount, currency
FROM cost_records
WHERE provider = ?
GROUP BY period_start, currency
ORDER BY period_start ASC
`

type GetMonthlyCostTrendRow struct {
	PeriodStart string          `json:"period_start"`
	TotalAmount sql.NullFloat64 `json:"total_amount"`
	Currency    string          `json:"currency"`
}

func (q *Queries) GetMonthlyCostTrend(ctx context.Context, provider string) ([]GetMonthlyCostTrendRow, error) {
	rows, err := q.db.QueryContext(ctx, getMonthlyCostTrend, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyCostTrendRow{}
	for rows.Next() {
		var i GetMonthlyCostTrendRow
		if err := rows.Scan(&i.PeriodStart, &i.TotalAmount, &i.Currency); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyCostTrendByService = `-- name: GetMonthlyCostTrendByService :many
SELECT period_start, SUM(amount) AS total_amount, currency
FROM cost_records
WHERE provider = ? AND service = ?
GROUP BY period_start, currency
ORDER BY period_start ASC
`

type GetMonthlyCostTrendByServiceParams struct {
	Provider string `json:"provider"`
	Service  string `json:"service"`
}

type GetMonthlyCostTrendByServiceRow struct {
	PeriodStart string          `json:"period_start"`
	TotalAmount sql.NullFloat64 `json:"total_amount"`
	Currency    string          `json:"currency"`
}

func (q *Queries) GetMonthlyCostTrendByService(ctx context.Context, arg GetMonthlyCostTrendByServiceParams) ([]GetMonthlyCostTrendByServiceRow, error) {
	rows, err := q.db.QueryContext(ctx, getMonthlyCostTrendByService, arg.Provider, arg.Service)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyCostTrendByServiceRow{}
	for rows.Next() {
		var i GetMonthlyCostTrendByServiceRow
		if err := rows.Scan(&i.PeriodStart, &i.TotalAmount, &i.Currency); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalCostByRegion = `-- name: GetTotalCostByRegion :many
SELECT region, SUM(amount) AS total_amount, currency
FROM cost_records
WHERE provider = ? AND period_start >= ? AND period_end <= ?
GROUP BY region, currency
ORDER BY total_amount DESC
`

type GetTotalCostByRegionParams struct {
	Provider    string `json:"provider"`
	PeriodStart string `json:"period_start"`
	PeriodEnd   string `json:"period_end"`
}

type GetTotalCostByRegionRow struct {
	Region      sql.NullString  `json:"region"`
	TotalAmount sql.NullFloat64 `json:"total_amount"`
	Currency    string          `json:"currency"`
}

func (q *Queries) GetTotalCostByRegion(ctx context.Context, arg GetTotalCostByRegionParams) ([]GetTotalCostByRegionRow, error) {
	rows, err := q.db.QueryContext(ctx, getTotalCostByRegion, arg.Provider, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTotalCostByRegionRow{}
	for rows.Next() {
		var i GetTotalCostByRegionRow
		if err := rows.Scan(&i.Region, &i.TotalAmount, &i.Currency); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalCostByService = `-- name: GetTotalCostByService :many
SELECT service, SUM(amount) AS total_amount, currency
FROM cost_records
WHERE provider = ? AND period_start >= ? AND period_end <= ?
GROUP BY service, currency
ORDER BY total_amount DESC
`

type GetTotalCostByServiceParams struct {
	Provider    string `json:"provider"`
	PeriodStart string `json:"period_start"`
	PeriodEnd   string `json:"period_end"`
}

type GetTotalCostByServiceRow struct {
	Service     string          `json:"service"`
	TotalAmount sql.NullFloat64 `json:"total_amount"`
	Currency    string          `json:"currency"`
}

func (q *Queries) GetTotalCostByService(ctx context.Context, arg GetTotalCostByServiceParams) ([]GetTotalCostByServiceRow, error) {
	rows, err := q.db.QueryContext(ctx, getTotalCostByService, arg.Provider, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTotalCostByServiceRow{}
	for rows.Next() {
		var i GetTotalCostByServiceRow
		if err := rows.Scan(&i.Service, &i.TotalAmount, &i.Currency); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCostRecord = `-- name: UpsertCostRecord :exec
INSERT INTO cost_records (provider, account_id, service, region, period_start, period_end, granularity, amount, currency, synced_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(provider, account_id, service, region, period_start, granularity)
DO UPDATE SET
    period_end = excluded.period_end,
    amount = excluded.amount,
    currency = excluded.currency,
    synced_at = excluded.synced_at
`

type UpsertCostRecordParams struct {
	Provider    string         `json:"provider"`
	AccountID   string         `json:"account_id"`
	Service     string         `json:"service"`
	Region      sql.NullString `json:"region"`
	PeriodStart string         `json:"period_start"`
	PeriodEnd   string         `json:"period_end"`
	Granularity string         `json:"granularity"`
	Amount      float64        `json:"amount"`
	Currency    string         `json:"currency"`
	SyncedAt    string         `json:"synced_at"`
}

func (q *Queries) UpsertCostRecord(ctx context.Context, arg UpsertCostRecordParams) error {
	_, err := q.db.ExecContext(ctx, upsertCostRecord,
		arg.Provider,
		arg.AccountID,
		arg.Service,
		arg.Region,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Granularity,
		arg.Amount,
		arg.Currency,
		arg.SyncedAt,
	)
	return err
}
