// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type Commitment struct {
	ID                 int64   `json:"id"`
	Provider           string  `json:"provider"`
	AccountID          string  `json:"account_id"`
	CommitmentType     string  `json:"commitment_type"`
	PeriodStart        string  `json:"period_start"`
	PeriodEnd          string  `json:"period_end"`
	TotalCommitment    float64 `json:"total_commitment"`
	UsedCommitment     float64 `json:"used_commitment"`
	OnDemandEquivalent float64 `json:"on_demand_equivalent"`
	NetSavings         float64 `json:"net_savings"`
	UtilizationPct     float64 `json:"utilization_pct"`
	CoveragePct        float64 `json:"coverage_pct"`
	Currency           string  `json:"currency"`
	SyncedAt           string  `json:"synced_at"`
}

type Config struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type CostRecord struct {
	ID          int64          `json:"id"`
	Provider    string         `json:"provider"`
	AccountID   string         `json:"account_id"`
	Service     string         `json:"service"`
	Region      sql.NullString `json:"region"`
	PeriodStart string         `json:"period_start"`
	PeriodEnd   string         `json:"period_end"`
	Granularity string         `json:"granularity"`
	Amount      float64        `json:"amount"`
	Currency    string         `json:"currency"`
	SyncedAt    string         `json:"synced_at"`
}

type Resource struct {
	ID           int64          `json:"id"`
	Provider     string         `json:"provider"`
	AccountID    string         `json:"account_id"`
	Service      string         `json:"service"`
	ResourceID   string         `json:"resource_id"`
	ResourceType string         `json:"resource_type"`
	Name         sql.NullString `json:"name"`
	Region       sql.NullString `json:"region"`
	Spec         sql.NullString `json:"spec"`
	Tags         sql.NullString `json:"tags"`
	State        sql.NullString `json:"state"`
	DiscoveredAt string         `json:"discovered_at"`
}

type SyncHistory struct {
	ID             int64          `json:"id"`
	Provider       string         `json:"provider"`
	AccountID      string         `json:"account_id"`
	Region         sql.NullString `json:"region"`
	PeriodStart    string         `json:"period_start"`
	PeriodEnd      string         `json:"period_end"`
	CostRecords    sql.NullInt64  `json:"cost_records"`
	ResourcesFound sql.NullInt64  `json:"resources_found"`
	StartedAt      string         `json:"started_at"`
	CompletedAt    sql.NullString `json:"completed_at"`
}
