// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources.sql

package store

import (
	"context"
	"database/sql"
)

const countResources = `-- name: CountResources :one
SELECT COUNT(*) FROM resources
`

func (q *Queries) CountResources(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countResources)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countResourcesByAccount = `-- name: CountResourcesByAccount :many
SELECT account_id, COUNT(*) AS count FROM resources
WHERE provider = ?
GROUP BY account_id
ORDER BY count DESC
`

type CountResourcesByAccountRow struct {
	AccountID string `json:"account_id"`
	Count     int64  `json:"count"`
}

func (q *Queries) CountResourcesByAccount(ctx context.Context, provider string) ([]CountResourcesByAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, countResourcesByAccount, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountResourcesByAccountRow{}
	for rows.Next() {
		var i CountResourcesByAccountRow
		if err := rows.Scan(&i.AccountID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countResourcesByProvider = `-- name: CountResourcesByProvider :one
SELECT COUNT(*) FROM resources WHERE provider = ?
`

func (q *Queries) CountResourcesByProvider(ctx context.Context, provider string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countResourcesByProvider, provider)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countResourcesByService = `-- name: CountResourcesByService :many
SELECT service, COUNT(*) AS count FROM resources
WHERE provider = ?
GROUP BY service
ORDER BY count DESC
`

type CountResourcesByServiceRow struct {
	Service string `json:"service"`
	Count   int64  `json:"count"`
}

func (q *Queries) CountResourcesByService(ctx context.Context, provider string) ([]CountResourcesByServiceRow, error) {
	rows, err := q.db.QueryContext(ctx, countResourcesByService, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountResourcesByServiceRow{}
	for rows.Next() {
		var i CountResourcesByServiceRow
		if err := rows.Scan(&i.Service, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSpotInstances = `-- name: CountSpotInstances :one
SELECT COUNT(*) FROM resources
WHERE provider = ? AND resource_type = 'ec2:instance' AND spec LIKE '%"lifecycle":"spot"%'
`

func (q *Queries) CountSpotInstances(ctx context.Context, provider string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSpotInstances, provider)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteResourcesByAccount = `-- name: DeleteResourcesByAccount :exec
DELETE FROM resources WHERE provider = ? AND account_id = ?
`

type DeleteResourcesByAccountParams struct {
	Provider  string `json:"provider"`
	AccountID string `json:"account_id"`
}

func (q *Queries) DeleteResourcesByAccount(ctx context.Context, arg DeleteResourcesByAccountParams) error {
	_, err := q.db.ExecContext(ctx, deleteResourcesByAccount, arg.Provider, arg.AccountID)
	return err
}

const deleteResourcesByProvider = `-- name: DeleteResourcesByProvider :exec
DELETE FROM resources WHERE provider = ?
`

func (q *Queries) DeleteResourcesByProvider(ctx context.Context, provider string) error {
	_, err := q.db.ExecContext(ctx, deleteResourcesByProvider, provider)
	return err
}

const getResourcesByAccount = `-- name: GetResourcesByAccount :many
SELECT id, provider, account_id, service, resource_id, resource_type, name, region, spec, tags, state, discovered_at FROM resources
WHERE provider = ? AND account_id = ?
ORDER BY service, resource_type
`

type GetResourcesByAccountParams struct {
	Provider  string `json:"provider"`
	AccountID string `json:"account_id"`
}

func (q *Queries) GetResourcesByAccount(ctx context.Context, arg GetResourcesByAccountParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, getResourcesByAccount, arg.Provider, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.AccountID,
			&i.Service,
			&i.ResourceID,
			&i.ResourceType,
			&i.Name,
			&i.Region,
			&i.Spec,
			&i.Tags,
			&i.State,
			&i.DiscoveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourcesByProvider = `-- name: GetResourcesByProvider :many
SELECT id, provider, account_id, service, resource_id, resource_type, name, region, spec, tags, state, discovered_at FROM resources
WHERE provider = ?
ORDER BY service, resource_type
`

func (q *Queries) GetResourcesByProvider(ctx context.Context, provider string) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, getResourcesByProvider, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.AccountID,
			&i.Service,
			&i.ResourceID,
			&i.ResourceType,
			&i.Name,
			&i.Region,
			&i.Spec,
			&i.Tags,
			&i.State,
			&i.DiscoveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourcesByRegion = `-- name: GetResourcesByRegion :many
SELECT id, provider, account_id, service, resource_id, resource_type, name, region, spec, tags, state, discovered_at FROM resources
WHERE provider = ? AND region = ?
ORDER BY service, resource_type
`

type GetResourcesByRegionParams struct {
	Provider string         `json:"provider"`
	Region   sql.NullString `json:"region"`
}

func (q *Queries) GetResourcesByRegion(ctx context.Context, arg GetResourcesByRegionParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, getResourcesByRegion, arg.Provider, arg.Region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.AccountID,
			&i.Service,
			&i.ResourceID,
			&i.ResourceType,
			&i.Name,
			&i.Region,
			&i.Spec,
			&i.Tags,
			&i.State,
			&i.DiscoveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourcesByService = `-- name: GetResourcesByService :many
SELECT id, provider, account_id, service, resource_id, resource_type, name, region, spec, tags, state, discovered_at FROM resources
WHERE provider = ? AND service = ?
ORDER BY resource_type, name
`

type GetResourcesByServiceParams struct {
	Provider string `json:"provider"`
	Service  string `json:"service"`
}

func (q *Queries) GetResourcesByService(ctx context.Context, arg GetResourcesByServiceParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, getResourcesByService, arg.Provider, arg.Service)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.AccountID,
			&i.Service,
			&i.ResourceID,
			&i.ResourceType,
			&i.Name,
			&i.Region,
			&i.Spec,
			&i.Tags,
			&i.State,
			&i.DiscoveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourcesByServiceAndRegion = `-- name: GetResourcesByServiceAndRegion :many
SELECT id, provider, account_id, service, resource_id, resource_type, name, region, spec, tags, state, discovered_at FROM resources
WHERE provider = ? AND service = ? AND region = ?
ORDER BY resource_type, name
`

type GetResourcesByServiceAndRegionParams struct {
	Provider string         `json:"provider"`
	Service  string         `json:"service"`
	Region   sql.NullString `json:"region"`
}

func (q *Queries) GetResourcesByServiceAndRegion(ctx context.Context, arg GetResourcesByServiceAndRegionParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, getResourcesByServiceAndRegion, arg.Provider, arg.Service, arg.Region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.AccountID,
			&i.Service,
			&i.ResourceID,
			&i.ResourceType,
			&i.Name,
			&i.Region,
			&i.Spec,
			&i.Tags,
			&i.State,
			&i.DiscoveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertResource = `-- name: UpsertResource :exec
INSERT INTO resources (provider, account_id, service, resource_id, resource_type, name, region, spec, tags, state, discovered_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(provider, account_id, resource_id)
DO UPDATE SET
    service = excluded.service,
    resource_type = excluded.resource_type,
    name = excluded.name,
    region = excluded.region,
    spec = excluded.spec,
    tags = excluded.tags,
    state = excluded.state,
    discovered_at = excluded.discovered_at
`

type UpsertResourceParams struct {
	Provider     string         `json:"provider"`
	AccountID    string         `json:"account_id"`
	Service      string         `json:"service"`
	ResourceID   string         `json:"resource_id"`
	ResourceType string         `json:"resource_type"`
	Name         sql.NullString `json:"name"`
	Region       sql.NullString `json:"region"`
	Spec         sql.NullString `json:"spec"`
	Tags         sql.NullString `json:"tags"`
	State        sql.NullString `json:"state"`
	DiscoveredAt string         `json:"discovered_at"`
}

func (q *Queries) UpsertResource(ctx context.Context, arg UpsertResourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertResource,
		arg.Provider,
		arg.AccountID,
		arg.Service,
		arg.ResourceID,
		arg.ResourceType,
		arg.Name,
		arg.Region,
		arg.Spec,
		arg.Tags,
		arg.State,
		arg.DiscoveredAt,
	)
	return err
}
