// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_history.sql

package store

import (
	"context"
	"database/sql"
)

const countSyncHistory = `-- name: CountSyncHistory :one
SELECT COUNT(*) FROM sync_history
`

func (q *Queries) CountSyncHistory(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSyncHistory)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLatestSync = `-- name: GetLatestSync :one
SELECT id, provider, account_id, region, period_start, period_end, cost_records, resources_found, started_at, completed_at FROM sync_history
WHERE provider = ? AND account_id = ?
ORDER BY started_at DESC
LIMIT 1
`

type GetLatestSyncParams struct {
	Provider  string `json:"provider"`
	AccountID string `json:"account_id"`
}

func (q *Queries) GetLatestSync(ctx context.Context, arg GetLatestSyncParams) (SyncHistory, error) {
	row := q.db.QueryRowContext(ctx, getLatestSync, arg.Provider, arg.AccountID)
	var i SyncHistory
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.AccountID,
		&i.Region,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CostRecords,
		&i.ResourcesFound,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getLatestSyncByProvider = `-- name: GetLatestSyncByProvider :one
SELECT id, provider, account_id, region, period_start, period_end, cost_records, resources_found, started_at, completed_at FROM sync_history
WHERE provider = ?
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSyncByProvider(ctx context.Context, provider string) (SyncHistory, error) {
	row := q.db.QueryRowContext(ctx, getLatestSyncByProvider, provider)
	var i SyncHistory
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.AccountID,
		&i.Region,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CostRecords,
		&i.ResourcesFound,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getSyncHistory = `-- name: GetSyncHistory :many
SELECT id, provider, account_id, region, period_start, period_end, cost_records, resources_found, started_at, completed_at FROM sync_history
ORDER BY started_at DESC
`

func (q *Queries) GetSyncHistory(ctx context.Context) ([]SyncHistory, error) {
	rows, err := q.db.QueryContext(ctx, getSyncHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncHistory{}
	for rows.Next() {
		var i SyncHistory
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.AccountID,
			&i.Region,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.CostRecords,
			&i.ResourcesFound,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncHistoryByProvider = `-- name: GetSyncHistoryByProvider :many
SELECT id, provider, account_id, region, period_start, period_end, cost_records, resources_found, started_at, completed_at FROM sync_history
WHERE provider = ?
ORDER BY started_at DESC
`

func (q *Queries) GetSyncHistoryByProvider(ctx context.Context, provider string) ([]SyncHistory, error) {
	rows, err := q.db.QueryContext(ctx, getSyncHistoryByProvider, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncHistory{}
	for rows.Next() {
		var i SyncHistory
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.AccountID,
			&i.Region,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.CostRecords,
			&i.ResourcesFound,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSyncHistory = `-- name: InsertSyncHistory :one
INSERT INTO sync_history (provider, account_id, region, period_start, period_end, cost_records, resources_found, started_at, completed_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertSyncHistoryParams struct {
	Provider       string         `json:"provider"`
	AccountID      string         `json:"account_id"`
	Region         sql.NullString `json:"region"`
	PeriodStart    string         `json:"period_start"`
	PeriodEnd      string         `json:"period_end"`
	CostRecords    sql.NullInt64  `json:"cost_records"`
	ResourcesFound sql.NullInt64  `json:"resources_found"`
	StartedAt      string         `json:"started_at"`
	CompletedAt    sql.NullString `json:"completed_at"`
}

func (q *Queries) InsertSyncHistory(ctx context.Context, arg InsertSyncHistoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertSyncHistory,
		arg.Provider,
		arg.AccountID,
		arg.Region,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.CostRecords,
		arg.ResourcesFound,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateSyncHistoryCompleted = `-- name: UpdateSyncHistoryCompleted :exec
UPDATE sync_history
SET cost_records = ?, resources_found = ?, completed_at = ?
WHERE id = ?
`

type UpdateSyncHistoryCompletedParams struct {
	CostRecords    sql.NullInt64  `json:"cost_records"`
	ResourcesFound sql.NullInt64  `json:"resources_found"`
	CompletedAt    sql.NullString `json:"completed_at"`
	ID             int64          `json:"id"`
}

func (q *Queries) UpdateSyncHistoryCompleted(ctx context.Context, arg UpdateSyncHistoryCompletedParams) error {
	_, err := q.db.ExecContext(ctx, updateSyncHistoryCompleted,
		arg.CostRecords,
		arg.ResourcesFound,
		arg.CompletedAt,
		arg.ID,
	)
	return err
}
